set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets cpu/fetcher_m/opcode[28]];
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets cpu/fetcher_m/read1[4]_INST_0_i_1_n_1];


set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

set_property PACKAGE_PIN J17 [get_ports AN0]
set_property PACKAGE_PIN J18 [get_ports AN1]
set_property PACKAGE_PIN T9 [get_ports AN2]
set_property PACKAGE_PIN J14 [get_ports AN3]
set_property PACKAGE_PIN P14 [get_ports AN4]
set_property PACKAGE_PIN T14 [get_ports AN5]
set_property PACKAGE_PIN K2 [get_ports AN6]
set_property PACKAGE_PIN U13 [get_ports AN7]
set_property PACKAGE_PIN T10 [get_ports CA]
set_property PACKAGE_PIN R10 [get_ports CB]
set_property PACKAGE_PIN K16 [get_ports CC]
set_property PACKAGE_PIN K13 [get_ports CD]
set_property PACKAGE_PIN P15 [get_ports CE]
set_property PACKAGE_PIN T11 [get_ports CF]
set_property PACKAGE_PIN L18 [get_ports CG]
set_property PACKAGE_PIN H15 [get_ports DP]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports AN0]
set_property IOSTANDARD LVCMOS33 [get_ports AN1]
set_property IOSTANDARD LVCMOS33 [get_ports AN2]
set_property IOSTANDARD LVCMOS33 [get_ports AN3]
set_property IOSTANDARD LVCMOS33 [get_ports AN4]
set_property IOSTANDARD LVCMOS33 [get_ports AN5]
set_property IOSTANDARD LVCMOS33 [get_ports AN6]
set_property IOSTANDARD LVCMOS33 [get_ports AN7]
set_property IOSTANDARD LVCMOS33 [get_ports CA]
set_property IOSTANDARD LVCMOS33 [get_ports CB]
set_property IOSTANDARD LVCMOS33 [get_ports CC]
set_property IOSTANDARD LVCMOS33 [get_ports CD]
set_property IOSTANDARD LVCMOS33 [get_ports CE]
set_property IOSTANDARD LVCMOS33 [get_ports CF]
set_property IOSTANDARD LVCMOS33 [get_ports CG]
set_property IOSTANDARD LVCMOS33 [get_ports DP]


set_property PACKAGE_PIN C12 [get_ports rst_PB_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_PB_in]
